### ISSUE TITLE
Archiv-Dienst für wenig genutzte, große Inhalte.

### ISSUE THREAD

**Issue by mkarg** [ijug-ev/infra#1]
In der NextCloud liegen auch Roh-Dateien für Videos. Wenn diese geschnitten und veröffentlicht sind, werden diese eigentlich kaum noch gebraucht. Der Speicherplatz auf der NextCloud ist eigentlich zu wertvoll dafür.

**Comment by mkarg** [comment]
@JOpsDev und @mkarg haben die Idee, eine Hetzner-Storage Box (bereits bestellt) via WebDAV als External Storage in NextCloud zu veröffentlichen. Wir warten derzeit auf die Bereitstellung der Storage Box. Wir nutzen kein SMB/CIFS (das schneller als WebDAV wäre), weil auf der NextClound-VM kein Samba / webfs installiert ist.

Nächster Schritt: Sobald die Storage Box bereits steht...
- [ ] Folder einrichten auf der Storage Box und diesen via WebDAV freigeben (nicht den Root-Folder, damit wir die Storage Box auch für anderen Zwecke, z. B. internes Backup, nutzen können).
- [ ] External Storage in NextCloud einbinen.
- [ ] External Storage in NextCloud freigeben für die Endnutzer.

**Comment by mkarg** [comment]
Wer auch immer das hier haben wollte, bitte melden. Wir wollen den Task schließen, aber die Dateien sind nocht nicht verschoben!

**Comment by McPringle** [comment]
Das Archiv wurde konfiguriert und die Cyberland-Leute informiert. Viel Spass!
